### ISSUE TITLE
Remove or keep link from locust?

### ISSUE THREAD

**Issue by justiniso** [cicada-load/cicada#12]
Project currently indicates the fork from locust:

![](http://i.imgur.com/AQy1iJt.png)

Do we want to keep that around for clarity or scrap it? I can ask support to convert to a normal repo.

**Comment by jinxcat** [comment]
I don't think we should remove the link to the original project.

**Comment by jmelfi** [comment]
I think we keep it for now until we verify if we are going to go back to locust or stay here in cicada as discussed in issue #13.

If we continue to move forward, we may want to remove this fork reference and keep it in the readme/description.  At some point we won't be able to merge from locust upstream or them pull from us in any meaningful way.  I'm fine either way since it doesn't _really_ affect anything.
