### ISSUE TITLE
Push rights granted on Locust, continue with Locust or Cicada?

### ISSUE THREAD

**Issue by alexandrul** [cicada-load/cicada#13]
https://github.com/locustio/locust/issues/355#issuecomment-198276046

**Comment by justiniso** [comment]
I'm torn. On the one hand, good to keep the community centralized. But if the owners don't respond again, you can have all of the maintainers in the world and it won't matter because you can't release a new version. 

Either way you all want to go, I'm keeping the fork open just in case.

**Comment by jmelfi** [comment]
I'd personally like to keep the community centralized since a break will cause fragmentation of the community using and working to maintain and contribute.  I do worry that with the events in life that the maintainers have had, it may be better to keep with cicada since we control the release cycle.  

I'm good with either move.  I feel a bit of caution still since it took so long to get the push rights, I'm not sure if this solves the issue of no releases moving forward due to overburdened maintainers.  I'm unsure of the better option here.

**Comment by cgoldberg** [comment]
keeping the Locust name and project space would be nice.

> because you can't release a new version.

fwiw, the PyPI namespace "locustio" and is owned by heyman

hopefully we can get access to publish releases via PyPI.
If so, I'm +1 on canceling the fork and working under the existing locust project on GitHub.

**Comment by pmdarrow** [comment]
I agree with @cgoldberg, if we can get access to publish via PyPI then there's no need to keep this fork. Let's keep it open until we get that access though.

**Comment by justiniso** [comment]
I think we're all in agreement, moving forward with locustio/locust.
